import type { QuestionnaireConfig } from "../types";

export const realEstateQuestionnaire: QuestionnaireConfig = {
  id: "real-estate",
  categoryLabel: "Real Estate",
  questions: [
    {
      key: "business_type",
      title: "Which of the following best describes your real estate business?",
      type: "multi-select-expandable",
      initialOptions: [
        "Residential Property Sales",
        "Luxury Residential Properties",
        "Commercial Real Estate",
        "Property Investment Advisory",
        "Other",
      ],
      allOptions: [
        "Residential Property Sales",
        "Luxury Residential Properties",
        "Commercial Real Estate",
        "Industrial Real Estate",
        "Plotted Developments & Land Sales",
        "Property Leasing & Rentals",
        "Property Management Services",
        "Real Estate Development",
        "Property Investment Advisory",
        "Real Estate Consultancy",
      ],
    },
    {
      key: "offerings",
      title: "Which properties, services, or offerings would you like to prominently showcase on your website?",
      type: "multi-select-expandable",
      initialOptions: ["Apartments", "Villas", "Commercial Offices", "Investment Consulting", "Other"],
      allOptions: [
        "Apartments",
        "Villas",
        "Luxury Homes",
        "Commercial Offices",
        "Retail Spaces",
        "Warehouses",
        "Industrial Properties",
        "Residential Plots",
        "Agricultural Land",
        "Rental Properties",
        "Property Management Services",
        "Investment Consulting",
        "Legal & Documentation Assistance",
        "New Launch Projects",
        "Ready-to-Move Properties",
      ],
    },
    {
      key: "objective_and_strengths",
      title: "What is the primary objective of your website, and what distinguishes your business from competitors?",
      type: "composite-objective",
      sections: [
        {
          key: "primary_objective",
          title: "Primary Objective",
          type: "single",
          options: [
            "Generate Property Enquiries",
            "Schedule Site Visits",
            "Receive WhatsApp Enquiries",
            "Generate Consultation Requests",
            "Collect Investor Leads",
            "Showcase Available Properties",
            "Strengthen Brand Presence",
          ],
        },
        {
          key: "key_strengths",
          title: "Key Business Strengths",
          type: "multi-expandable",
          initialOptions: [
            "Exclusive Property Listings",
            "Verified & Legally Approved Properties",
            "Investment Advisory Services",
            "Transparent Pricing & Dealings",
            "Other",
          ],
          allOptions: [
            "Exclusive Property Listings",
            "Verified & Legally Approved Properties",
            "Luxury Property Expertise",
            "Strong Local Market Knowledge",
            "Investment Advisory Services",
            "End-to-End Buying Assistance",
            "Property Financing Assistance",
            "Fast Transaction Process",
            "Large Property Portfolio",
            "Premium Customer Service",
            "Experienced Industry Professionals",
            "Transparent Pricing & Dealings",
            "Strong Developer Network",
            "Property Management Support",
            "NRI Investment Assistance",
            "Customized Property Solutions",
          ],
        },
      ],
    },
    {
      key: "website_sections",
      title: "Which sections would you like to include in your website?",
      type: "multi-select-all",
      allOptions: [
        "Homepage",
        "Company Profile",
        "Property Portfolio",
        "Featured Projects",
        "Services",
        "Investment Opportunities",
        "Testimonials",
        "Gallery",
        "Market Insights / Blog",
        "FAQ",
        "Contact Us",
        "Careers",
        "Custom Sections",
      ],
    },
    {
      key: "design_preferences",
      title: "Design & Branding Preferences",
      type: "design-preferences",
      initialOptions: [
        "Clean & Minimal",
        "Premium & Elegant",
        "Modern & Contemporary",
        "Corporate & Professional",
        "Other",
      ],
      allOptions: [
        "Luxury Real Estate Style",
        "Bold & High-Converting",
        "Dark Theme",
        "Light Theme",
      ],
    },
    {
      key: "business_assets",
      title: "Please upload any business assets you would like us to use while creating your website.",
      type: "file-upload",
      uploadCategories: [
        "Company Logo",
        "Brand Guidelines",
        "Property Images",
        "Project Brochures",
        "Team Photographs",
        "Corporate Presentation",
        "Promotional Videos",
        "Existing Marketing Materials",
      ],
    },
    {
      key: "business_emphasis",
      title: "Which aspects of your business would you like your website to emphasize the most?",
      type: "multi-select-expandable",
      initialOptions: [
        "Premium Property Portfolio",
        "Investment Opportunities",
        "Property Listings",
        "Brand Reputation & Experience",
        "Other",
      ],
      allOptions: [
        "Premium Property Portfolio",
        "Ongoing & Completed Projects",
        "Investment Opportunities",
        "Property Listings",
        "Luxury Real Estate Services",
        "Commercial Property Solutions",
        "Property Management Services",
        "NRI Property Assistance",
        "Legal & Documentation Support",
        "Developer Partnerships",
        "Customer Success Stories",
        "Market Expertise & Insights",
        "End-to-End Buying Assistance",
        "Rental & Leasing Solutions",
        "Brand Reputation & Experience",
        "Team & Leadership",
        "Technology & Innovation",
        "Exclusive Property Access",
      ],
    },
    {
      key: "website_features",
      title: "Which website features and experiences would you like us to prioritize?",
      type: "feature-timeline",
      timelineSteps: [
        {
          key: "visual_experience",
          title: "Visual Experience",
          options: [
            "Full-Screen Property Showcase",
            "Large Image Galleries",
            "Premium Animations",
            "Modern Interactive Effects",
            "Video Background Sections",
            "Minimalistic Layout",
          ],
        },
        {
          key: "lead_generation",
          title: "Lead Generation",
          options: [
            "Sticky WhatsApp Button",
            "Instant Callback Form",
            "Property Inquiry Forms",
            "Consultation Booking",
            "Lead Capture Popups",
          ],
        },
        {
          key: "trust_credibility",
          title: "Trust & Credibility",
          options: [
            "Client Testimonials",
            "Success Stories",
            "Awards & Recognition",
            "Partner & Developer Showcase",
            "Certifications & Accreditations",
          ],
        },
        {
          key: "content_marketing",
          title: "Content & Marketing",
          options: [
            "Blog / Insights Section",
            "Investment Resources",
            "Downloadable Brochures",
            "FAQs",
            "Market Updates",
          ],
        },
        {
          key: "premium_features",
          title: "Premium Features",
          options: [
            "Interactive Property Listings",
            "Featured Projects Showcase",
            "Advanced Search Experience",
            "Virtual Property Tours",
            "Interactive Maps",
          ],
        },
      ],
    },
  ],
};
