import type { QuestionConfig } from "../types";

export const REAL_ESTATE_SECTIONS = [
  { key: "business-identification", title: "Business Identification" },
  { key: "website-goal", title: "Website Goal" },
  { key: "property-information", title: "Property Information" },
  { key: "contact-lead", title: "Contact & Lead System" },
  { key: "team", title: "Team Information" },
  { key: "trust", title: "Trust & Credibility" },
  { key: "features", title: "Website Features" },
  { key: "branding", title: "Branding" },
  { key: "content", title: "Content Generation" },
  { key: "media", title: "Media" },
  { key: "automation", title: "Automation Settings" },
] as const;

export const REAL_ESTATE_QUESTIONS: QuestionConfig[] = [
  {
    key: "business_type",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "What best describes your real estate business?",
    type: "single-select",
    options: [
      "Property Developer / Builder",
      "Real Estate Agency / Brokerage",
      "Luxury Real Estate Firm",
      "Commercial Real Estate",
      "Property Management Company",
      "Independent Realtor",
    ],
    required: true,
  },
  {
    key: "business_name",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "What is your business name?",
    type: "text",
    placeholder: "Enter your business name",
    required: true,
  },
  {
    key: "has_logo",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "Do you already have a logo?",
    type: "single-select",
    options: ["Yes (Upload)", "No (Generate Logo)"],
    required: true,
  },
  {
    key: "logo_upload",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "Upload your logo",
    subtitle: "PNG, SVG, or JPG recommended.",
    type: "file-upload",
    uploadCategories: ["Logo"],
    showWhen: { questionKey: "has_logo", equals: "Yes (Upload)" },
    required: true,
  },
  {
    key: "primary_location",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "What is your primary business location?",
    placeholder: "Bangalore, Karnataka",
    example: "Bangalore, Karnataka",
    type: "text",
    required: true,
  },
  {
    key: "services",
    section: "business-identification",
    sectionTitle: "Business Identification",
    title: "Which services do you offer?",
    type: "multi-select",
    options: [
      "Property Sales",
      "Property Rentals",
      "Property Leasing",
      "Property Management",
      "Investment Consulting",
      "Property Valuation",
      "Legal Assistance",
    ],
    required: true,
  },
  {
    key: "website_goal",
    section: "website-goal",
    sectionTitle: "Website Goal",
    title: "What is the main goal of your website?",
    subtitle: "This single answer heavily influences homepage design.",
    type: "single-select",
    options: [
      "Generate Property Leads",
      "Sell New Projects",
      "Get Site Visit Bookings",
      "Showcase Portfolio",
      "Generate Rental Inquiries",
      "Attract Investors",
    ],
    required: true,
  },
  {
    key: "property_data_method",
    section: "property-information",
    sectionTitle: "Property Information",
    title: "How would you like to add your properties?",
    subtitle: "AI will parse PDFs and Excel automatically.",
    type: "single-select",
    options: [
      "Upload Property Excel Sheet",
      "Upload PDF Brochure",
      "Enter Manually",
      "I Don't Have Property Data Yet",
    ],
    required: true,
  },
  {
    key: "property_count",
    section: "property-information",
    sectionTitle: "Property Information",
    title: "Approximately how many active properties/projects do you currently have?",
    type: "single-select",
    options: ["1–10", "11–50", "51–200", "200+"],
    required: true,
  },
  {
    key: "property_types",
    section: "property-information",
    sectionTitle: "Property Information",
    title: "Which property types do you deal with?",
    type: "multi-select",
    options: [
      "Apartments",
      "Villas",
      "Plots",
      "Commercial Offices",
      "Retail Shops",
      "Warehouses",
      "Industrial Properties",
      "Luxury Homes",
    ],
    required: true,
  },
  {
    key: "sell_rent",
    section: "property-information",
    sectionTitle: "Property Information",
    title: "Do you sell, rent, or both?",
    type: "single-select",
    options: ["Sell Only", "Rent Only", "Both"],
    required: true,
  },
  {
    key: "contact_methods",
    section: "contact-lead",
    sectionTitle: "Contact & Lead System",
    title: "How should customers contact you?",
    type: "multi-select",
    options: ["Phone Call", "WhatsApp", "Email", "Inquiry Form"],
    required: true,
  },
  {
    key: "book_site_visits",
    section: "contact-lead",
    sectionTitle: "Contact & Lead System",
    title: "Do you want visitors to book site visits online?",
    type: "single-select",
    options: ["Yes", "No"],
    required: true,
  },
  {
    key: "site_visit_availability",
    section: "contact-lead",
    sectionTitle: "Contact & Lead System",
    title: "Site visits available:",
    type: "single-select",
    options: ["Weekdays", "Weekends", "Both"],
    showWhen: { questionKey: "book_site_visits", equals: "Yes" },
    required: true,
  },
  {
    key: "showcase_team",
    section: "team",
    sectionTitle: "Team Information",
    title: "Would you like to showcase your team/agents?",
    type: "single-select",
    options: ["Yes", "No"],
    required: true,
  },
  {
    key: "team_members",
    section: "team",
    sectionTitle: "Team Information",
    title: "Upload team members",
    subtitle: "Add photo, name, designation, phone, and email for each team member.",
    type: "repeatable",
    showWhen: { questionKey: "showcase_team", equals: "Yes" },
    repeatableFields: [
      { key: "photo", label: "Photo", type: "file" },
      { key: "name", label: "Name", type: "text", placeholder: "Full name", required: true },
      { key: "designation", label: "Designation", type: "text", placeholder: "Senior Agent", required: true },
      { key: "phone", label: "Phone", type: "text", placeholder: "+91 98765 43210" },
      { key: "email", label: "Email", type: "text", placeholder: "agent@company.com" },
    ],
    required: true,
  },
  {
    key: "trust_credentials",
    section: "trust",
    sectionTitle: "Trust & Credibility",
    title: "Do you have any of the following?",
    type: "multi-select",
    options: [
      "RERA Registration",
      "Industry Certifications",
      "Awards",
      "Press Mentions",
      "None",
    ],
    required: true,
  },
  {
    key: "completed_transactions",
    section: "trust",
    sectionTitle: "Trust & Credibility",
    title: "How many successful transactions/projects have you completed?",
    type: "text",
    placeholder: "e.g. 150+",
    required: true,
  },
  {
    key: "testimonials",
    section: "trust",
    sectionTitle: "Trust & Credibility",
    title: "Do you have client testimonials?",
    type: "single-select",
    options: ["Upload Testimonials", "Generate Later"],
    required: true,
  },
  {
    key: "website_features",
    section: "features",
    sectionTitle: "Website Features",
    title: "Select the features you want.",
    type: "multi-select",
    options: [
      "Property Search",
      "Advanced Filters",
      "Property Comparison",
      "Save Favorites",
      "Brochure Download",
      "EMI Calculator",
      "Google Maps",
      "WhatsApp Chat",
      "Virtual Tours",
    ],
    required: true,
  },
  {
    key: "website_style",
    section: "branding",
    sectionTitle: "Branding",
    title: "Choose your preferred website style.",
    subtitle: "This maps directly to template selection.",
    type: "single-select",
    options: [
      "Modern Corporate",
      "Luxury Premium",
      "Minimal Clean",
      "Bold Sales Focused",
      "High-End International",
    ],
    required: true,
  },
  {
    key: "color_style",
    section: "branding",
    sectionTitle: "Branding",
    title: "Choose your preferred color style.",
    type: "single-select",
    options: ["Blue Professional", "Black Luxury", "Green Modern", "Custom"],
    required: true,
  },
  {
    key: "business_description",
    section: "content",
    sectionTitle: "Content Generation",
    title: "Tell us about your business in a few sentences.",
    subtitle: "AI generates homepage copy, about page, service descriptions, SEO content, and CTA text from this answer.",
    example: "We have been selling residential and commercial properties in Bangalore since 2014.",
    type: "textarea",
    placeholder: "Describe your business...",
    required: true,
  },
  {
    key: "business_differentiator",
    section: "content",
    sectionTitle: "Content Generation",
    title: "What makes your business different?",
    example: "We specialize in luxury villas and offer end-to-end legal assistance.",
    type: "textarea",
    placeholder: "Your unique value proposition...",
    required: true,
  },
  {
    key: "media_uploads",
    section: "media",
    sectionTitle: "Media",
    title: "Upload any available media.",
    subtitle: "Optional — AI organizes them automatically.",
    type: "file-upload",
    uploadCategories: ["Logo", "Property Photos", "Team Photos", "Brochures", "Videos"],
    required: false,
  },
  {
    key: "ai_auto_generate",
    section: "automation",
    sectionTitle: "Automation Settings",
    title: "Would you like AI to automatically generate:",
    type: "multi-select",
    options: [
      "Homepage Content",
      "About Us Page",
      "Property Descriptions",
      "SEO Metadata",
      "FAQs",
      "Blog Content",
    ],
    defaultValue: [
      "Homepage Content",
      "About Us Page",
      "Property Descriptions",
      "SEO Metadata",
      "FAQs",
      "Blog Content",
    ],
    required: true,
  },
];

export function getVisibleQuestions(answers: Record<string, unknown>): QuestionConfig[] {
  return REAL_ESTATE_QUESTIONS.filter((q) => {
    if (!q.showWhen) return true;
    const answer = answers[q.showWhen.questionKey];
    if (q.showWhen.equals !== undefined) return answer === q.showWhen.equals;
    if (q.showWhen.includes !== undefined) {
      return Array.isArray(answer) && answer.includes(q.showWhen.includes);
    }
    return true;
  });
}

export function getProgressPercent(stepIndex: number, answers: Record<string, unknown>): number {
  const visible = getVisibleQuestions(answers);
  if (visible.length === 0) return 0;
  return Math.round(((stepIndex + 1) / visible.length) * 100);
}

export function getQuestionByIndex(index: number, answers: Record<string, unknown>): QuestionConfig | null {
  const visible = getVisibleQuestions(answers);
  return visible[index] ?? null;
}

export function getTotalQuestionCount(answers: Record<string, unknown>): number {
  return getVisibleQuestions(answers).length;
}
